[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Robot Co-Simulator"
authors = [{name = "Dima Nikiforov", email = "vnikiforov@berkeley.edu"}, {name = "Chris Dong", email = "chrisdong@berkeley.edu"}]
dynamic = ["version", "description"]
